spring:
 profiles:
    active:
    - dev
    
---
server:
  port: 8004
  
spring:
  profiles: dev
  application:
    name: microservicecloud-config-dept-client
  
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: kayak.entity    # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件
    

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloudDB01              # 数据库名称
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
      
eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://eureka7004.com:7004/eureka/
      #,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
      #http://localhost:7001/eureka，实现集群后服务需要注册到所有的eureka集群
  instance:
    instance-id: microservicecloud-dept-8004          #自定义服务名称信息
    prefer-ip-address: true                                         #访问路径可以显示ip地址
    
info:
  app.name: kayak-microservicecloud
  company.name: www.kyak.com  
  build.artifactid: $project.artifactId$
  build.version:  $project.version$
  
---
server:
  port: 8004
  
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: kayak.entity    # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件
    
spring:
 profiles: test
 application:
    name: microservicecloud-config-dept-client

 datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloudDB02              # 数据库名称
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
      
eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://eureka7004.com:7004/eureka/
      #,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
      #http://localhost:7001/eureka，实现集群后服务需要注册到所有的eureka集群
  instance:
    instance-id: microservicecloud-dept-8004          #自定义服务名称信息
    prefer-ip-address: true                                         #访问路径可以显示ip地址
    
info:
  app.name: kayak-microservicecloud
  company.name: www.kyak.com  
  build.artifactid: $project.artifactId$
  build.version:  $project.version$
  

  